Standardize shell script help text output

diff --git a/scripts/deploy-ebook-to-www b/scripts/deploy-ebook-to-www
--- a/scripts/deploy-ebook-to-www
+++ b/scripts/deploy-ebook-to-www
@@ -1,50 +1,63 @@
 #!/bin/bash
 set -e
 
+source "$(dirname "${BASH_SOURCE[0]}")/lib/common.sh"
+
 usage(){
-	fmt <<EOF
-DESCRIPTION
-	Deploy a Standard Ebook source repository to the web.
+print_help \
+ "[command]$(basename $BASH_SOURCE)[/] [-v,--verbose] [-g,--group [parameter]<GROUP>[/]] [-l,--last-push-hash [parameter]<HASH>[/]] [--no-build] [--no-bulk-downloads] [--no-epubcheck] [--no-images] [--no-recompose] [--no-feeds] [--web-root [path][parameter]<WEBROOT>[/]] [--web-url [parameter]<WEB_URL>[/]] [path][parameter]<SE_EBOOK_REPO_PATH>[/] [[path][parameter]<SE_EBOOK_REPO_PATH>[/] ...]" \
+ "$(cat << EOF
+Deploy Standard Ebook source repositories in [path][parameter]<SE_EBOOK_REPO_PATH>[/] to the website running on the local machine.
+EOF
+)"\
+ "$(cat << EOF
+-v,--verbose
 
-USAGE
-	deploy-ebook-to-www [-v,--verbose] [-g,--group GROUP] [--webroot WEBROOT] [--weburl WEBURL] [--no-images] [--no-build] [--no-epubcheck] [--no-recompose] [--no-feeds] [--no-bulk-downloads] [-l,--last-push-hash HASH] DIRECTORY [DIRECTORY...]
-		DIRECTORY is a bare source repository.
-		GROUP is a groupname. Defaults to \`se\`.
-		WEBROOT is the path to your webroot. Defaults to \`/standardebooks.org/web/www\`.
-		WEBURL is the URL the website is served on. Defaults to \`https://standardebooks.org\`.
+	Increase output verbosity.
 
-		The deploy process does four things:
+-g,--group [parameter]<GROUP>[/]
 
-		1. Build distributable ebook files using \`se build\`.
+	The group who will own the deployed files; defaults to [parameter]se[/].
 
-		2. Build single-page and toc-based web-readable versions using \`se recompose-epub\`.
+-l,--last-push-hash [parameter]<HASH>[/]
 
-		3. Generate various images and thumbnails for web use.
+	Check the repo head against this hash to see if the cover image or ebook source changed, which will determine if cover thumbnails get re-generated or the ebook gets rebuilt.
 
-		4. Generates RSS/Atom/OPDS feeds, but only if no other tasks are queued behind this one.
+--no-build
 
-		5. Generate bulk download files, but only if no other tasks are queued behind this one.
+	Don't run [command]se build[/] or [command]se recompose-epub[/] to create distributable ebook files or web-readable versions.
 
-		With --no-images, don't create cover thumbnails or hero images for the web.
+--no-bulk-downloads
 
-		With --no-build, don't run \`se build\` or \`se recompose-epub\` to create distributable ebook files or web-readable versions.
+	Don't generate bulk download zip files.
 
-		With --no-epubcheck, run \`se build\` instead of \`se build --check\`.
+--no-epubcheck
 
-		With --no-recompose, don't run \`se recompose-epub\` to generate single-page output.
+	Run [command]se build[/] instead of [command]se build --check[/].
 
-		With --last-push-hash, check the repo head against HASH to see if the cover image or ebook source changed, which will determine if cover thumbnails get re-generated or the ebook gets rebuilt.
+--no-images
 
-		With --no-feeds, don't generate RSS/Atom/OPDS feeds.
+	Don't create cover thumbnails or hero images for the web.
 
-		With --no-bulk-downloads, don't generate bulk download files.
+--no-recompose
+
+	Don't run [command]se recompose-epub[/] to generate single-page output.
+
+--no-feeds
+
+	Don't generate RSS/Atom/OPDS feeds.
+
+--web-root [path][parameter]<WEB_ROOT>[/]
+
+	Specify a different root folder for the S.E. website on the local machine; defaults to [path]/standardebooks.org/web/www[/].
+
+--web-url [parameter]<WEB_URL>[/]
+
+	Specify a different base URL folder for the S.E. website; defaults to [url]https://standardebooks.org[/].
 
 EOF
-	exit
+)"
 }
-die(){ printf "\033[0;7;31mError:\033[0m %s\n" "${1}" 1>&2; exit 1; }
-require(){ command -v "$1" > /dev/null 2>&1 || { suggestion=""; if [ -n "$2" ]; then suggestion=" $2"; fi; die "$1 is not installed.${suggestion}"; } }
-# End boilerplate
 
 verbose="false"
 images="true"
@@ -58,14 +71,12 @@ recompose="true"
 feeds="true"
 bulkDownloads="true"
 
-if [ $# -eq 0 ]; then
+if [ $# -eq 0 ] || { [ $# -eq 1 ] && { [ "$1" = "--help" ] || [ "$1" = "-h" ]; }; }; then
 	usage
 fi
 
 while [ $# -gt 0 ]; do
 	case "$1" in
-		-h|--help)
-			usage ;;
 		-v|--verbose)
 			verbose="true"
 			shift 1
@@ -75,12 +86,12 @@ while [ $# -gt 0 ]; do
 			group="$2"
 			shift 2
 			;;
-		--webroot)
+		--web-root)
 			[ -n "$2" ] || die "Web root can’t be empty."
 			webRoot="$2"
 			shift 2
 			;;
-		--weburl)
+		--web-url)
 			[ -n "$2" ] || die "Web URL can’t be empty."
 			webUrl="$2"
 			shift 2
@@ -173,7 +184,7 @@ do
 	fi
 
 	if ! pushd "${repoDir}" > /dev/null; then
-		echo "Couldn't cd into ${repoDir}. Skipping."
+		printf "$(colorize_usage "Couldn't enter [path]${repoDir}[/], skipping.")\n"
 		continue
 	fi
 
