Add --group parameter.

diff --git a/scripts/deploy-ebook-to-www b/scripts/deploy-ebook-to-www
--- a/scripts/deploy-ebook-to-www
+++ b/scripts/deploy-ebook-to-www
@@ -6,8 +6,9 @@ DESCRIPTION
 	Deploy a Standard Ebook source repository to the web.
 
 USAGE
-	deploy-ebook-to-www [-v,--verbose] DIRECTORY [DIRECTORY...]
+	deploy-ebook-to-www [-v,--verbose] [-g,--group GROUP] DIRECTORY [DIRECTORY...]
 		DIRECTORY is a bare source repository.
+		GROUP is a groupname. Defaults to "se".
 EOF
 	exit
 }
@@ -16,6 +17,7 @@ require(){ command -v "$1" > /dev/null 2>&1 || { suggestion=""; if [ -n "$2" ]; 
 # End boilerplate
 
 verbose="false"
+group="se"
 
 if [ $#  -eq 0 ]; then
 	usage
@@ -29,9 +31,18 @@ while [ $# -gt 0 ]; do
 			verbose="true"
 			shift 1
 			;;
+		-g|--group)
+			[ -n "$2" ] || die "Group cannot be empty."
+			group="$2"
+			shift 2
+			;;
 		*) break ;;
 	esac
 done
+
+if ! [ "$(getent group "${group}")" ]; then
+	die "Group ${group} does not exist. Either use --group or create the group."
+fi
 
 # Check for dependencies
 require "convert" "Try: apt-get install imagemagick"
@@ -127,7 +138,7 @@ do
 	mv "${imgWorkDir}/${urlSafeIdentifier}@2x.jpg" "${imgWorkDir}/${urlSafeIdentifier}-cover@2x.jpg"
 	mv "${imgWorkDir}/${urlSafeIdentifier}.jpg" "${imgWorkDir}/${urlSafeIdentifier}-cover.jpg"
 
-	sudo chgrp --preserve-root --recursive se "${imgWorkDir}/${urlSafeIdentifier}"*
+	sudo chgrp --preserve-root --recursive "${group}" "${imgWorkDir}/${urlSafeIdentifier}"*
 	sudo chmod --preserve-root --recursive g+w "${imgWorkDir}/${urlSafeIdentifier}"*
 
 	if [ "${verbose}" = "true" ]; then
@@ -164,10 +175,10 @@ do
 	# Delete the now-empty work dir (empty except for .git)
 	rm --preserve-root --recursive --force "${workDir}" "${imgWorkDir}"
 
-	sudo chgrp --preserve-root --recursive se "${webDir}"
+	sudo chgrp --preserve-root --recursive "${group}" "${webDir}"
 	sudo chmod --preserve-root --recursive g+ws "${webDir}"
 
-	sudo chgrp --preserve-root --recursive se "/standardebooks.org/www/images/covers/"
+	sudo chgrp --preserve-root --recursive "${group}" "/standardebooks.org/www/images/covers/"
 	sudo chmod --preserve-root --recursive g+ws "/standardebooks.org/www/images/covers/"
 
 	if [ "${verbose}" = "true" ]; then
